name: Auto assign

on: workflow_call

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Assign Action
        uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          configuration-path: './.github/workflows/config/reviewers.yml'
