name: Exec project
description: Exec each project

inputs:
  script:
    description: Script name
    required: true
  project:
    description: Project name
    required: true

runs:
  using: composite
  steps:
    - name: Execute project
      shell: bash
      working-directory: ${{ inputs.project }}
      run: |
        sh ${{ input.script }}
