name: Exec project
description: Exec each project

inputs:
  project:
    description: Project name
    required: true

runs:
  using: composite
  steps:
    - name : Project A
      if: inputs.project == 'projectA'
      run: |
        sh a.sh
      shell: bash
      working-directory: projectA

    - name : Project B
      if: inputs.project == 'projectB'
      run: |
        sh b.sh
      shell: bash
      working-directory: projectB

    - name : Project C
      if: inputs.project == 'projectC'
      run: |
        sh c.sh
      shell: bash
      working-directory: projectC
