name: Exec project
description: Exec each project

inputs:
  project:
    description: Project name
    required: true

runs:
  using: composite
  steps:
    - uses: ./.github/workflows/composite/setup-path
      id: script
      with:
        project: ${{ inputs.project }}

    - name: Execute project
      shell: bash
      working-directory: ${{ inputs.project }}
      run: |
        sh ${{ steps.script.outputs.path }}
        
