name: CI

on:
  pull_request:

jobs:
  path-filter:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@1ec7035ff53cbd7a98744bd986f6ca1c7e17d1cb
        id: filter
        with:
          filters: ./.github/workflows/config/filter.yml

  hellos:
    needs: path-filter
    runs-on: ubuntu-latest
    if: needs.path-filter.outputs.projects != '[]'
    strategy:
      matrix:
        project: ${{ fromJson(needs.path-filter.outputs.projects) }}
    steps:
      - uses: actions/checkout@v3

      - uses: ./.github/workflows/composite/setup-path
        id: setup-path
        with:
          project: ${{ matrix.project }}

      - uses: ./.github/workflows/composite/exec
        with:
          script: ${{ steps.setup-path.outputs.path }}
          project: ${{ matrix.project }}
