name: CI

on:
  pull_request:

jobs:
  path-filter:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: ./.github/workflows/config/filter.yml

  hellos:
    needs: path-filter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: ${{ fromJson(needs.path-filter.outputs.projects }}
    steps:
      - uses: actions/checkout@v3

      - name: Exec ${{ matrix.project }}
        uses: ./.github/workflows/composite/exec
        with:
          project: ${{ matrix.project }}
